There has been a change in the method run, in the section of code starting on line nr 300.
  
The change is in a catch statement, in a try statement, in a catch statement, in a try statement, in the method ```run```, in the class ```1```, in an initialization, in the invocation ```execute```, in the method ```messageReceived```, in the class ```StartRecoveryTransportRequestHandler```, in the class ```RecoverySource```.
  
The following changes have been made:  
Changed type reference from ```java.io.IOException``` to ```Exception``` on line 300.  
