There has been a change in the method run, in the section of code starting on line nr 157.
  
The change is in a catch statement, in a try statement, in the method ```run```, in the class ```1```, in an initialization, in the invocation ```execute```, in a for each statement, in the method ```doStop```, in the class ```InternalIndicesService```.
  
The following changes have been made:  
Changed type reference from ```java.lang.Exception``` to ```Throwable``` on line 157.  
